[profile.default]
solc = "0.8.24"
optimizer = true
optimizer_runs = 800
via_ir = true

src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts-ccip/=lib/ccip/contracts/",
    "@prb/math/=lib/prb-math/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"

]
